### ISSUE TITLE
chalk dependency

### ISSUE THREAD

**Issue by gpltaylor** [0x20h/dockerfiles#3]
I am getting the following error when running command

docker run -v $PWD:/project 0x20h/create-react-app my-react-project

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-react-app/index.js:41:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by 0x20h** [comment]
I removed the auto update, image should rebuild. Thanks for reporting.
https://github.com/0x20h/dockerfiles/commit/5199505c861c2a16c311b6835c13c3adef73fed5
